# Input Settings: initialize base input folder names, 
# dataset collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "simulated"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   ex_filename: scRNA-Seqexpression file name
    #
    #   pt_filename: a file containing pseudotime ordering
    #
    datasets:
        - name: "dataset1"
          ex_filename: "exp_train.txt"
          pt_filename: "time_train.txt"



    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:
        - name: "SCODE"
          params:
              should_run: [True]
              nGenes: [100]
              z: [4]
              nCells: [356]         
              iIter: [100]
              nRep: [2]

        - name: "SCNS"
          params: 
              should_run: [False]

              


# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
