# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "simulated"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   ex_filename: scRNA-Seqexpression file name
    #
    #   pt_filename: a file containing pseudotime ordering
    #
    datasets:
        - name: "HSC"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"

#        - name: "HSC_ics1_dropped"
#          exprData: "ExpressionData-dropped.csv"
#          cellData: "PseudoTime-dropped.csv"
#          trueEdges: "refNetwork.csv"



    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:
        - name: "SCODE"
          params:
              should_run: [False]
              z: [10]
              nIter: [100]
              nRep: [5]

        #- name: "SCNS"
        #  params: 
        #      should_run: [False]
              
              
        - name: "SINCERITIES"
          params: 
              should_run: [False]
                            
              
        - name: "PIDC"
          params: 
              should_run: [True]


        - name: "GRNVBEM"
          params: 
              should_run: [False]

              

        - name: "GENIE3"
          params: 
              should_run: [False]
              
              
              
        - name: "GRNBOOST2"
          params: 
              should_run: [False]
              
              
              
        - name: "LEAP"
          params: 
              should_run: [False]
              # Recommended maxLag value is 0.3
              # but it is very slow with 0.3
              # when we have more than 1000 cells.
              maxLag: [0.8]

              
                            
        - name: "JUMP3"
          params: 
              should_run: [False]

              
              
        - name: "PPCOR"
          params: 
              should_run: [False]
              # Used in parsing output
              pVal: [0.01]
              
              
              
        - name: "GRISLI"
          params: 
              should_run: [False]
              L: [10]
              R: [1000]
              alphaMin: [0.3]


        - name: "SCINGE"
          params: 
              should_run: [False]


        - name: "SCRIBE"
          params: 
              should_run: [False]
              ### required parameters
              # a list of delay values
              delay: ["20,25,50,75,100"]
              # any of 'RDI', 'uRDI', 'cRDI', or 'ucRDI'
              method: ['ucRDI']
              # lower detection limit (expression below this 
              # will be treated as zero.
              lowerDetectionLimit: [0]
              # expressionFamily: for synthetic data use uninormal
              #  for mRNA count data use negbinomial.size()
              expressionFamily: ['uninormal']
              ### optional but recommended parameters
              # log transform expression values or not
              log: [False]
              # ignore pseudotime values (and use experimental
              # time points instead), recommended True for synthetic data
              # False for real mRNA data
              ignorePT: [True]


# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
    output_prefix: "HSC"
